language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script: npm run build
deploy:
  api_key:
    secure: D5Ifm7mCJcJ0YSqLVzQlva/KPm+DJqBK7nCPYBFQITLfbkrPVXvJfvu3lY7wwDk+yRYr7wjhq8ljxvSrubzPhPqXyVE39AQxlEe0oHrhQXXRlxnWLhUGlkWIEQ5El+Uagi9ClnNEpZjfp/SFVw7tWZQDavhy9b9nAZEns/4IWF07wj6IdqqsVthOYy6o9nfWVpYBzLGZG02F41xSqZ+0ZRGwJR7udmUSiag3L8imTmtsIdAfMsf30pLPKVjIJ26Z8zYrD+/XfQ7zinqvc7CkceC1GL6RK1kgrwEFV+0nhRmqPF+L99CFp7VdYgQMEwlEUJlioIhaoa2Yu86vujqxOJDxqyAKjWnWedwufRRUzoOLKdzOyZC6EFgLvtO22yS1liBvgiIym25CldLR+dSMqsXa3h1RkYjSjtaaoCnWEb6cXlzW2pp37pwh80vT8rYs1zbY1bqutAWYcmpXPEpTNm5GhIAEmxvi9gE74gQ+HA28ZlF7VmcFdYH1C19PtsBy2Ff7xT78NlEj8lTMEGgB0oYiEv5WP61Due0KiQhgMcjUhZn6Q7pyLigfkrcIVM8bhi90TCJ9Ms/Q7ibBDPtr9lzaj5230yN2p7DC0255uSr/ZUVYUHWbqKSK3FYAqMAHUMlcZtSpII/Q3TgEjbrZNYYceyi+xAo0WagrbUNzY6Q=
